// ****** Licence ******
// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// ©Osynia2026

// ****** Version ******
//@version=6

// ****** Description de jackieTrade ******
// Mon script osyniaTrade

// ****** Declarations ******
indicator(
	title='osyniaTrade-0.1.1', 
	shorttitle = 'oTrade', 
	overlay=true, 
	max_labels_count=500
)

// ****** Import ******

// ****** Constantes ******
bearColor = color.red
bullColor = color.new(color.green, 0)
hiddenBullColor = color.new(color.green, 80)
hiddenBearColor = color.new(color.red, 80)
textColor = color.white
noneColor = color.new(color.gray, 100)

// ****** Inputs ******

// ===== PARAMÈTRES GENERAL =====
GRP_GENERAL = 'General'
plotSmaInput = input.bool(
	defval=true, title='Ind. SMA', group=GRP_GENERAL
)
plotRsiInput = input.bool(
	defval=false, title='Ind. RSI', group=GRP_GENERAL
)
plotMacdInput = input.bool(
	defval=false, title='Ind. MACD', group=GRP_GENERAL
)
plotVidyaInput = input.bool(
	defval=true, title='Ind. VIDYA', group=GRP_GENERAL
)

// ===== PARAMÈTRES MACD =====
GRP_MACD = 'MACD'
fastInput = input(1, 'rapide', group=GRP_MACD)
slowInput = input(60, 'Slow length', group=GRP_MACD)

// ===== PARAMÈTRES RSI =====
GRP_RSI = 'RSI'
lenRSIInput = input.int(title='Période du RSI', minval=1, defval=14, group=GRP_RSI)
srcRSIInput = input(title='RSI Source', defval=close, group=GRP_RSI)
// Nombre de bougies à gauche/droite pour détecter les pivots.
lbRRSIInput = input(title='Pivot Lookback Right', defval=5, display = display.none, group=GRP_RSI)
lbLRSIInput = input(title='Pivot Lookback Left', defval=5, display = display.none, group=GRP_RSI)
// Plage de recherche pour les divergences.
rangeUpperRSIInput = input(title='Max of Lookback Range', defval=60, display = display.none, group=GRP_RSI)
rangeLowerRSIInput = input(title='Min of Lookback Range', defval=5, display = display.none, group=GRP_RSI)
// Options pour afficher/masquer les divergences.
plotBullRSIInput = input(title='Plot Bullish', defval=true, display = display.none, group=GRP_RSI)
plotHiddenBullRSIInput = input(title='Plot Hidden Bullish', defval=false, display = display.none, group=GRP_RSI)
plotBearRSIInput = input(title='Plot Bearish', defval=true, display = display.none, group=GRP_RSI)
plotHiddenBearRSIInput = input(title='Plot Hidden Bearish', defval=false, display = display.none, group=GRP_RSI)

// ===== PARAMÈTRES SMA =====
GRP_SMA = 'SMA'
smaLongLengthInput = input.int(389, 'Long Length', minval=1, group = GRP_SMA)
smaSrcInput = input.source(close, 'Source', group = GRP_SMA)
smaOffsetInput = input.int(0, 'Offset', minval = -500, maxval = 500, display = display.none, group = GRP_SMA)
lengthSMAInput = input.int(13, "SMA Length", minval=1, group = GRP_SMA)
lengthEMAInput = input.int(25, "EMA Length", minval=1, group = GRP_SMA)

// ===== PARAMÈTRES VIDYA ====
GRP_VIDYA = 'VIDYA'
cmoCloseInput = input.int(6, "CMO Close", minval=1, group = GRP_VIDYA)
cmoHLInput = input.int(9, "CMO High/Low", minval=1, group = GRP_VIDYA)
emaPeriodInput = input.int(3, "EMA Period", minval=1, group = GRP_VIDYA)

// ****** Fonctions ******

// @function CMO (Chande Momentum Oscillator)
// - mesurer la force relative de la hausse et de la baisse d'un actif sur une période donnée.
// - +50 à +100 : Forte tendance haussière (surachat)
// - 0 à +50 : tendance modérée
// - 0 : equilibre
// - ne convient pas sur des actions peu volatiles
// - src - Source des données (ex : close, high, low)
// @param        src, period
// @returns      CMO, na si la somme est nulle
calculateCMO(src, period) =>
	// somme des hausses de prix sur les period dernières bougies
	up = math.sum(math.max(src - src[1], 0), period)
    down = math.sum(math.max(src[1] - src, 0), period)
	// calcul le ratio entre la somme des hausses et la somme des baisses
	CMO = (up + down) != 0 ? (up - down) / (up + down) * 100 : na

// @function VIDYA (Volatility Index Dynamic Average)
// - Le VIDYA est une moyenne mobile exponentielle (EMA) adaptative :
// - Quand le marché est volatile (CMO proche de ±100) → Le VIDYA réagit rapidement aux changements de prix (lissage faible).
// - Quand le marché est calme (CMO proche de 0) → Le VIDYA lisse davantage les données (réaction plus lente).
// - src - Source des données (ex : close, high, low)
// - periodCMO - Période pour calculer le CMO (utilisé pour mesurer la volatilité).
// - periodEMA - Période de base pour le lissage exponentiel (comme une EMA classique).
// @param src, periodCMO, periodEMA
// @returns      VIDYA
calculateVIDYA(src, periodCMO, periodEMA) =>
    var float vidya = na
   	// Mesurer la force de la tendance (volatilité directionnelle)
    cmo = calculateCMO(src, periodCMO)
   	// Facteur de lissage de base, plus periodEMA est grand, plus le lissage est fort (réaction lente)
    smoothFactor = 2.0 / (1.0 + periodEMA)
	// Calcul du CMO absolu (volatilité) - convertit le CMO en une valeur entre 0 et 1 
    absCMO = math.abs(cmo / 100)
	// Fonction recursive
	// Si vidya[1] est na (première valeur), alors vidya = src
	// Partie "nouvelle donnée" : src * smoothFactor * absCMO
	// Plus absCMO est proche de 1 (volatilité élevée), plus le poids de src est important → réaction rapide
	// Plus absCMO est proche de 0 (volatilité faible), plus le poids de src est faible → lissage fort.
	// Partie "historique" : vidya[1] * (1 - smoothFactor * absCMO)
	// conserve l’inertie des valeurs précédentes
    vidya := na(vidya[1]) ? src : src * smoothFactor * absCMO + vidya[1] * (1 - smoothFactor * absCMO)
    vidya


// ====== VIDYA ========
// ******* Calculs *****

cmo = calculateCMO(close, cmoCloseInput)
vidya = calculateVIDYA(src = close, periodCMO = cmoCloseInput, periodEMA = emaPeriodInput )

plot(
	plotVidyaInput ? vidya : na,
	color = color.blue,
	linewidth = 2,
)
// hline(5, "Overbought", color=color.red, linestyle=hline.style_dashed)
// hline(-5, "Oversold", color=color.green, linestyle=hline.style_dashed)
// hline(0, "Neutral", color=color.gray)

// ====== MACD =========
// ****** Calculs ******

// macd
[macdLine, signalLine, histLine] = ta.macd(close, fastInput, slowInput, 9)

// ****** Visuels ******
plot( 
	plotMacdInput ? macdLine : na, 
	color = color.red
)
plot(
	plotMacdInput ? signalLine : na, 
	color = color.yellow
)

// ====== RSI =========
// ****** Calculs ******
// rsi
osc = ta.rsi(srcRSIInput, lenRSIInput)
plFound = na(ta.pivotlow(osc, lbLRSIInput, lbRRSIInput)) ? false : true
phFound = na(ta.pivothigh(osc, lbLRSIInput, lbRRSIInput)) ? false : true

_inRange(cond) =>
	bars = ta.barssince(cond == true)
	rangeLowerRSIInput <= bars and bars <= rangeUpperRSIInput

//------------------------------------------------------------------------------
// Regular Bullish
// Osc: Higher Low
inRangePl = _inRange(plFound[1])
oscHL = osc[lbRRSIInput] > ta.valuewhen(plFound, osc[lbRRSIInput], 1) and inRangePl

// Price: Lower Low

priceLL = low[lbRRSIInput] < ta.valuewhen(plFound, low[lbRRSIInput], 1)
bullCondAlert = priceLL and oscHL and plFound
bullCond = plotBullRSIInput and bullCondAlert

//------------------------------------------------------------------------------
// Hidden Bullish
// Osc: Lower Low

oscLL = osc[lbRRSIInput] < ta.valuewhen(plFound, osc[lbRRSIInput], 1) and inRangePl

// Price: Higher Low

priceHL = low[lbRRSIInput] > ta.valuewhen(plFound, low[lbRRSIInput], 1)
hiddenBullCondAlert = priceHL and oscLL and plFound
hiddenBullCond = plotHiddenBullRSIInput and hiddenBullCondAlert

//------------------------------------------------------------------------------
// Regular Bearish
// Osc: Lower High
inRangePh = _inRange(phFound[1])
oscLH = osc[lbRRSIInput] < ta.valuewhen(phFound, osc[lbRRSIInput], 1) and inRangePh

// Price: Higher High

priceHH = high[lbRRSIInput] > ta.valuewhen(phFound, high[lbRRSIInput], 1)

bearCondAlert = priceHH and oscLH and phFound
bearCond = plotBearRSIInput and bearCondAlert

//------------------------------------------------------------------------------
// Hidden Bearish
// Osc: Higher High

oscHH = osc[lbRRSIInput] > ta.valuewhen(phFound, osc[lbRRSIInput], 1) and inRangePh

// Price: Lower High

priceLH = high[lbRRSIInput] < ta.valuewhen(phFound, high[lbRRSIInput], 1)

hiddenBearCondAlert = priceLH and oscHH and phFound
hiddenBearCond = plotHiddenBearRSIInput and hiddenBearCondAlert

// ****** Visuels ******

plot(
	plotRsiInput ? osc : na, 
	title="RSI", 
	linewidth=2, 
	color=#2962FF
)

hline(
	plotRsiInput ? 50 : na, 
	title="Middle Line", 
	color=#787B86, linestyle=hline.style_dotted
)
obLevel = hline(
	plotRsiInput ? 70 : na, 
	title="Overbought", 
	color=#787B86, linestyle=hline.style_dotted
)
osLevel = hline(
	plotRsiInput ? 30 : na, 
	title="Oversold", 
	color=#787B86, linestyle=hline.style_dotted
)
fill(obLevel, osLevel, 
	title="Background", color=color.rgb(33, 150, 243, 90)
)

plot(
     plFound and plotRsiInput ? osc[lbRRSIInput] : na,
     offset=-lbRRSIInput,
     title="Regular Bullish",
     linewidth=2,
     color=(bullCond ? bullColor : noneColor),
     style=plot.style_linebr,
	 display = display.pane,
	 editable = plotBullRSIInput
     )

plotshape(
	 bullCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bullish Label",
	 text="🟢  Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 editable = plotBullRSIInput
	 )

plot(
	 plFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bullish",
	 linewidth=2,
	 color=(hiddenBullCond ? hiddenBullColor : noneColor),
	 display = display.pane,
	 editable = plotHiddenBullRSIInput
	 )

plotshape(
	 hiddenBullCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bullish Label",
	 text=" H Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 editable = plotHiddenBullRSIInput
	 )

plot(
	 phFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bearish",
	 linewidth=2,
	 color=(bearCond ? bearColor : noneColor),
	 display = display.pane,
	 editable = plotBearRSIInput
	 )

plotshape(
	 bearCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bearish Label",
	 text=" Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 editable = plotBearRSIInput
	 )

plot(
	 phFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bearish",
	 linewidth=2,
	 color=(hiddenBearCond ? hiddenBearColor : noneColor),
	 display = display.pane,
	 editable = plotHiddenBearRSIInput
	 )

plotshape(
	 hiddenBearCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bearish Label",
	 text=" H Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 editable = plotHiddenBearRSIInput
	 )
// ====== SMA =========
// ****** Calculs ******
// calcul sma selon choix de la source
sma_var = ta.sma(smaSrcInput, lengthSMAInput)
ema_var = ta.ema(smaSrcInput, lengthEMAInput)
sellcondition = ta.crossover(sma_var, ema_var)
buycondition = ta.crossover(ema_var, sma_var)

// ****** Visuels ******
plot(
	plotSmaInput ? sma_var : na, 
	color = color.rgb(20, 62, 96), 
	title = "SMA", 
	offset = smaOffsetInput
)
plot(
	plotSmaInput ? ema_var : na, 
	color = color.red, 
	title = "SMA", 
	offset = smaOffsetInput
)
bgcolor(
	plotSmaInput and sellcondition ? color.orange: na
)
bgcolor(
	plotSmaInput and buycondition ? color.green: na
)
if sellcondition or buycondition
	line.new(
		x1 = bar_index -1,
		y1 = close,
		x2 = bar_index +1,
		y2 = close,
		color = color.black
	)


// ****** Strategies ******

// ****** Alertes ******

alertcondition(
	bullCondAlert, 
	title='Regular Bullish Divergence', 
	message="Found a new Regular Bullish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar")
alertcondition(
	hiddenBullCondAlert, 
	title='Hidden Bullish Divergence', 
	message='Found a new Hidden Bullish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
alertcondition(
	bearCondAlert, 
	title='Regular Bearish Divergence', 
	message='Found a new Regular Bearish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
alertcondition(
	hiddenBearCondAlert, 
	title='Hidden Bearish Divergence', 
	message='Found a new Hidden Bearish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
