// ****** Licence ******
// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// ©Osynia2026

// ****** Version ******
//@version=6

// ****** Description de osyniaTrade ******
// Mon script osyniaTrade
// Achat : Prix > VIDYA + confirmation par un autre indicateur (ex : RSI > 50).
// Vente : Prix < VIDYA + confirmation par un autre indicateur.
// Filtre de volatilité : Combiner avec l’ATR pour éviter les faux signaux en période de faible volatilité.

// ****** Declarations ******
indicator(
	title = 'osyniaTrade-0.1.3', 
	shorttitle = 'oTrade', 
	overlay = true, 
	max_labels_count = 500
)

// ****** Import ******

// ****** Constantes ******
bearColor = color.red
bullColor = color.new(color.green, 0)
hiddenBullColor = color.new(color.green, 80)
hiddenBearColor = color.new(color.red, 80)
textColor = color.white
noneColor = color.new(color.gray, 100)

// ****** Inputs ******

// ===== PARAMÈTRES GENERAL =====
GRP_GENERAL = 'General'
plotSmaInput = input.bool(
	defval=true, title='Ind. SMA', group=GRP_GENERAL
)
plotRsiInput = input.bool(
	defval=false, title='Ind. RSI', group=GRP_GENERAL
)
plotMacdInput = input.bool(
	defval=false, title='Ind. MACD', group=GRP_GENERAL
)
plotVidyaInput = input.bool(
	defval=true, title='Ind. VIDYA', group=GRP_GENERAL
)
plotBollingerInput = input.bool(
	defval=true, title='Ind. Bollinger', group=GRP_GENERAL
)

// ===== PARAMÈTRES MACD =====
GRP_MACD = 'MACD'
fastInput = input(1, 'rapide', group=GRP_MACD)
slowInput = input(60, 'Slow length', group=GRP_MACD)

// ===== PARAMÈTRES RSI =====
GRP_RSI = 'RSI'
lenRSIInput = input.int(title='Période du RSI', minval=1, defval=14, group=GRP_RSI)
srcRSIInput = input(title='RSI Source', defval=close, group=GRP_RSI)
// Nombre de bougies à gauche/droite pour détecter les pivots.
lbRRSIInput = input(title='Pivot Lookback Right', defval=5, display = display.none, group=GRP_RSI)
lbLRSIInput = input(title='Pivot Lookback Left', defval=5, display = display.none, group=GRP_RSI)
// Plage de recherche pour les divergences.
rangeUpperRSIInput = input(title='Max of Lookback Range', defval=60, display = display.none, group=GRP_RSI)
rangeLowerRSIInput = input(title='Min of Lookback Range', defval=5, display = display.none, group=GRP_RSI)
// Options pour afficher/masquer les divergences.
plotBullRSIInput = input(title='Plot Bullish', defval=true, display = display.none, group=GRP_RSI)
plotHiddenBullRSIInput = input(title='Plot Hidden Bullish', defval=false, display = display.none, group=GRP_RSI)
plotBearRSIInput = input(title='Plot Bearish', defval=true, display = display.none, group=GRP_RSI)
plotHiddenBearRSIInput = input(title='Plot Hidden Bearish', defval=false, display = display.none, group=GRP_RSI)
// Seuils de comparaison pour achat/vente avec vidya
rsiOverboughtInput = input(50, "Seuil RSI Achat")
rsiOversoldInput = input(50, "Seuil RSI Vente")

// ===== PARAMÈTRES SMA =====
GRP_SMA = 'SMA'
smaLongLengthInput = input.int(389, 'Long Length', minval=1, group = GRP_SMA)
smaSrcInput = input.source(close, 'Source', group = GRP_SMA)
smaOffsetInput = input.int(0, 'Offset', minval = -500, maxval = 500, display = display.none, group = GRP_SMA)
smaLengthInput = input.int(20, "SMA Length", minval=1, group = GRP_SMA)
emaPeriodInput = input.int(25, "EMA Length", minval=1, group = GRP_SMA)

// ===== PARAMÈTRES VIDYA ====
GRP_VIDYA = 'VIDYA'
cmoCloseInput = input.int(defval=6, title="CMO Close", minval=1, group = GRP_VIDYA)
cmoHLInput = input.int(defval=9, title="CMO High/Low", minval=1, group = GRP_VIDYA)
cmoPeriodeInput = input(defval=14, title="Période CMO pour VIDYA", group = GRP_VIDYA)

// ===== PARAMETRES BOLLINGER ====
GRP_BOLLINGER = 'BOLLINGER'
bollingerMultInput = input(defval=2.0, title="Multiplicateur écart-type", group=GRP_BOLLINGER)
bollingerSrcInput = input(defval=close, title='Source', group=GRP_BOLLINGER)


// ****** Fonctions ******

// @function CMO (Chande Momentum Oscillator)
// - mesurer la force relative de la hausse et de la baisse d'un actif sur une période donnée.
// - +50 à +100 : Forte tendance haussière (surachat)
// - 0 à +50 : tendance modérée
// - 0 : equilibre
// - ne convient pas sur des actions peu volatiles
// - src : Source des données (ex : close, high, low)
// @param        src, period
// @returns      CMO, na si la somme est nulle
calculateCMO(src, period) =>
	// somme des hausses de prix sur les period dernières bougies
	up = math.sum(math.max(src - src[1], 0), period)
    down = math.sum(math.max(src[1] - src, 0), period)
	// calcul le ratio entre la somme des hausses et la somme des baisses
	CMO = (up + down) != 0 ? (up - down) / (up + down) * 100 : na

// @function VIDYA (Volatility Index Dynamic Average)
// - Le VIDYA est une moyenne mobile exponentielle (EMA) adaptative :
// - Quand le marché est volatile (CMO proche de ±100) → Le VIDYA réagit rapidement aux changements de prix (lissage faible).
// - Quand le marché est calme (CMO proche de 0) → Le VIDYA lisse davantage les données (réaction plus lente).
// - src : Source des données (ex : close, high, low)
// - periodCMO : Période pour calculer le CMO (utilisé pour mesurer la volatilité).
// - periodEMA : Période de base pour le lissage exponentiel (comme une EMA classique).
// @param src, periodCMO, periodEMA
// @returns      VIDYA
calculateVIDYA(src, periodCMO, periodEMA) =>
    var float vidya = na
   	// Mesurer la force de la tendance (volatilité directionnelle)
    cmo = calculateCMO(src, periodCMO)
   	// Facteur de lissage de base, plus periodEMA est grand, plus le lissage est fort (réaction lente)
    smoothFactor = 2.0 / (1.0 + periodEMA)
	// Calcul du CMO absolu (volatilité) - convertit le CMO en une valeur entre 0 et 1 
    absCMO = math.abs(cmo / 100)
	// Fonction recursive
	// Si vidya[1] est na (première valeur), alors vidya = src
	// Partie "nouvelle donnée" : src * smoothFactor * absCMO
	// Plus absCMO est proche de 1 (volatilité élevée), plus le poids de src est important → réaction rapide
	// Plus absCMO est proche de 0 (volatilité faible), plus le poids de src est faible → lissage fort.
	// Partie "historique" : vidya[1] * (1 - smoothFactor * absCMO)
	// conserve l’inertie des valeurs précédentes
    vidya := na(vidya[1]) ? src : src * smoothFactor * absCMO + vidya[1] * (1 - smoothFactor * absCMO)
    vidya

// @function Fonction pour calculer le RSI
// - src : Source des données (ex : close, high, low)
// - rsiLength : Période du RSI
calculateRSI(src, rsiLength) =>
    ta.rsi(src, rsiLength)

// @function donne les conditions d'achat et de vente
// - buyCondition : true si Prix > VIDYA ET RSI > 50
// - sellCondition : true si Prix < VIDYA ET RSI < 50 (ou autre seuil)
// - src : Source des données (ex : close, high, low)
// - periodCMO : Période pour calculer le CMO (utilisé pour mesurer la volatilité).
// - periodEMA : Période de base pour le lissage exponentiel (comme une EMA classique).
// - rsiLength : Période du RSI
// - rsiOverbought et rsiOversold (seuils pour le RSI, par défaut 50)
checkConditionRsi(src, periodCMO, periodEMA, rsiLength, rsiOverbought, rsiOversold) =>
	vidya = calculateVIDYA(src, periodCMO, periodEMA)
	rsi = calculateRSI(src, rsiLength)
	buyCondition = (src > vidya) and (rsi > rsiOverbought)
	sellCondition = (src < vidya) and (rsi < rsiOversold)
	[buyCondition, sellCondition]

// @function     Fonction pour obtenir le timeframe supérieur
// @param        tf
// @returns      timeframe supérieur
getNextTimeframe(tf) =>
    if tf == '1'
        '5'
    else if tf == '5'
        '15'
    else if tf == '15'
        '60'
    else if tf == '60'
        '240'
    else if tf == '240'
        'D'
    else if tf == 'D'
        'W'
    else if tf == 'W'
        'M'
    else if tf == 'M'
        '3M'
    else if tf == '3M'
        '12M'
    else
        '12M'

// @function     Fonction pour trouver les 5 TPs les plus proches
// @param        all_tps, entry_price, is_long
// @returns      nearest_tps
findNearestTPs(all_tps, entry_price, is_long) =>
    var nearest_tps = array.new_float(5, 0.0)
    array.sort(all_tps, is_long ? order.ascending : order.descending)

    count = 0
    for i = 0 to array.size(all_tps) - 1 by 1
        tp = array.get(all_tps, i)
        if is_long and tp > entry_price or not is_long and tp < entry_price
            array.set(nearest_tps, count, tp)
            count := count + 1
            if count == 5
                break

    nearest_tps

// @function     Calcul de la pente
// - Elle permet de quantifier la force et la direction d'une tendance en mesurant l'inclinaison 
// de la droite de régression linéaire entre deux points.
// - Cas d'usage 1 : N'acheter que si la pente du prix est > 10° (tendance haussière forte)
// calculateSlopeAngle(close, 14) > 10
// - Cas d'usage 2 : Acheter si la pente du prix > pente de l'EMA (tendance haussière confirmée)
// priceSlope > emaSlope and priceSlope > 0, avec priceSlope = calculateSlopeAngle(close, 14)
// et emaSlope = calculateSlopeAngle(ema20, 14) sachant ema20 = ta.ema(close, 20)
// - src : Source des données (ex : close, high, low)
// - length : Nombre de périodes pour calculer la pente
// attention : un length trop petit et la pente sera trop volatile, un length trop grand et la pente sera trop 
// lissée
// @param        src, length
// @returns      slope
calculateSlopeAngle(src, length) =>
    rad2degree = 180 / math.pi // environ 57.5958
	// Calcul de la pente en radians
	// nz() (non-zero) remplace les valeurs na (non disponibles) par 0.
    // (src - nz(src[length])) / length : Pente moyenne sur length périodes (variation par unité de temps)
	// Exemple : Si src = close et length = 10, alors close - close[10] donne la variation du prix sur 10 bougies.
	pente = src - nz(src[length])
	// calcul l'arc tangeante : La pente d'une droite est liée à son angle par la relation tan(θ) = (Δy / Δx)
	// bar_index >= length pour ignorer les premieres valeurs car cela fausse le calcul de la pente
	slope = bar_index >= length ? rad2degree * math.atan(pente / length) : na
    slope

// @function donne les conditions d'achat et de vente
// - buyCondition : vidya_close > sma and vidya_high > sma
// - sellCondition : vidya_close < sma and vidya_low < sma
// - cmoClose : Période pour calculer le CMO de cloture.
// - cmoHL : Période pour calculer le CMO High/Low
// - periodEMA : Période de base pour le lissage exponentiel (comme une EMA classique).
// - smaLength : Période du SMA
checkConditionSma(cmoClose = 6, cmoHL = 9, periodEMA = 3, smaLength = 9) =>
	vidya_close = calculateVIDYA(close, cmoClose, periodEMA)
    vidya_high = calculateVIDYA(high, cmoHL, periodEMA)
    vidya_low = calculateVIDYA(low, cmoHL, periodEMA)
    sma = ta.sma(close, smaLength)
	buyCondition = vidya_close > sma and vidya_high > sma
    sellCondition = vidya_close < sma and vidya_low < sma
	[buyCondition, sellCondition]

// ====== INDICATEUR BOLLINGER ======
// ******* Calculs *******
// Bande centrale (SMA)
basis = ta.sma(bollingerSrcInput, smaLengthInput)
// Écart-type × multiplicateur
dev = bollingerMultInput * ta.stdev(bollingerSrcInput, smaLengthInput) 
// Bande supérieure
upper = basis + dev 
// Bande inférieure
lower = basis - dev

// ******* Visuels *******
plot(basis, "Bande centrale", color=color.blue, linewidth=2)
plot(upper, "Bande supérieure", color=color.red, linewidth=1)
plot(lower, "Bande inférieure", color=color.green, linewidth=1)
fill(upper, lower, color=color.new(color.purple, 90), title="Zone de volatilité")

// ******* Alertes *******

// ====== INDICATEUR VIDYA ========
// ******* Calculs *****

cmo = calculateCMO(close, cmoCloseInput)
vidya = calculateVIDYA(src = close, periodCMO = cmoCloseInput, periodEMA = emaPeriodInput )
rsiValue = calculateRSI(close, lenRSIInput)
[buySignalRsi, sellSignalRsi] = checkConditionRsi(
	close, 
	cmoPeriodeInput, emaPeriodInput, 
	lenRSIInput,
	rsiOverboughtInput, rsiOversoldInput
)
[buySignalSma, sellSignalSma] = checkConditionSma(
	cmoCloseInput, cmoHLInput, emaPeriodInput, 
	smaLengthInput)


// ******* Visuels *****
// tracer vidya
plot(
	plotVidyaInput ? vidya : na,
	title = "VIDYA",
	color = color.rgb(239, 10, 121),
	linewidth = 2
)
// tracer rsi
plotchar(
	plotVidyaInput ? rsiValue : na, 
	title = "RSI-VIDYA", 
	color = color.purple, 
	char = '•'
)

// Signaux d'achat/vente
//plotshape(buySignalRsi, title="Buy Signal RSI", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small)
plotshape(buySignalSma, title="Buy Signal SMA", style=shape.triangleup, location=location.belowbar, color=color.olive, size=size.small)
//plotshape(sellSignalRsi, title="Sell Signal", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small)
plotshape(sellSignalSma, title="Sell Signal SMA", style=shape.triangledown, location=location.abovebar, color=color.fuchsia, size=size.small)


// ******* Alertes *****
alertcondition(buySignalRsi, title="Buy Alert Rsi", message="Achat : Prix > VIDYA + RSI > 50")
alertcondition(sellSignalRsi, title="Sell Alert Rsi", message="Vente : Prix < VIDYA + RSI < 50")

// hline(5, "Overbought", color=color.red, linestyle=hline.style_dashed)
// hline(-5, "Oversold", color=color.green, linestyle=hline.style_dashed)
// hline(0, "Neutral", color=color.gray)

// ====== MACD =========
// ****** Calculs ******

// macd
[macdLine, signalLine, histLine] = ta.macd(close, fastInput, slowInput, 9)

// ****** Visuels ******
plot( 
	plotMacdInput ? macdLine : na, 
	color = color.red
)
plot(
	plotMacdInput ? signalLine : na, 
	color = color.yellow
)

// ====== RSI =========
// ****** Calculs ******
// rsi
osc = calculateRSI(srcRSIInput, lenRSIInput)
plFound = na(ta.pivotlow(osc, lbLRSIInput, lbRRSIInput)) ? false : true
phFound = na(ta.pivothigh(osc, lbLRSIInput, lbRRSIInput)) ? false : true

_inRange(cond) =>
	bars = ta.barssince(cond == true)
	rangeLowerRSIInput <= bars and bars <= rangeUpperRSIInput

//------------------------------------------------------------------------------
// Regular Bullish
// Osc: Higher Low
inRangePl = _inRange(plFound[1])
oscHL = osc[lbRRSIInput] > ta.valuewhen(plFound, osc[lbRRSIInput], 1) and inRangePl

// Price: Lower Low

priceLL = low[lbRRSIInput] < ta.valuewhen(plFound, low[lbRRSIInput], 1)
bullCondAlert = priceLL and oscHL and plFound
bullCond = plotBullRSIInput and bullCondAlert

//------------------------------------------------------------------------------
// Hidden Bullish
// Osc: Lower Low

oscLL = osc[lbRRSIInput] < ta.valuewhen(plFound, osc[lbRRSIInput], 1) and inRangePl

// Price: Higher Low

priceHL = low[lbRRSIInput] > ta.valuewhen(plFound, low[lbRRSIInput], 1)
hiddenBullCondAlert = priceHL and oscLL and plFound
hiddenBullCond = plotHiddenBullRSIInput and hiddenBullCondAlert

//------------------------------------------------------------------------------
// Regular Bearish
// Osc: Lower High
inRangePh = _inRange(phFound[1])
oscLH = osc[lbRRSIInput] < ta.valuewhen(phFound, osc[lbRRSIInput], 1) and inRangePh

// Price: Higher High

priceHH = high[lbRRSIInput] > ta.valuewhen(phFound, high[lbRRSIInput], 1)

bearCondAlert = priceHH and oscLH and phFound
bearCond = plotBearRSIInput and bearCondAlert

//------------------------------------------------------------------------------
// Hidden Bearish
// Osc: Higher High

oscHH = osc[lbRRSIInput] > ta.valuewhen(phFound, osc[lbRRSIInput], 1) and inRangePh

// Price: Lower High

priceLH = high[lbRRSIInput] < ta.valuewhen(phFound, high[lbRRSIInput], 1)

hiddenBearCondAlert = priceLH and oscHH and phFound
hiddenBearCond = plotHiddenBearRSIInput and hiddenBearCondAlert

// ****** Visuels ******

plot(
	plotRsiInput ? osc : na, 
	title="RSI", 
	linewidth=2, 
	color=#2962FF
)

hline(
	plotRsiInput ? 50 : na, 
	title="Middle Line", 
	color=#787B86, linestyle=hline.style_dotted
)
obLevel = hline(
	plotRsiInput ? 70 : na, 
	title="Overbought", 
	color=#787B86, linestyle=hline.style_dotted
)
osLevel = hline(
	plotRsiInput ? 30 : na, 
	title="Oversold", 
	color=#787B86, linestyle=hline.style_dotted
)
fill(obLevel, osLevel, 
	title="Background", color=color.rgb(33, 150, 243, 90)
)

plot(
     plFound and plotRsiInput ? osc[lbRRSIInput] : na,
     offset=-lbRRSIInput,
     title="Regular Bullish",
     linewidth=2,
     color=(bullCond ? bullColor : noneColor),
     style=plot.style_linebr,
	 display = display.pane,
	 editable = plotBullRSIInput
     )

plotshape(
	 bullCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bullish Label",
	 text="🟢  Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 editable = plotBullRSIInput
	 )

plot(
	 plFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bullish",
	 linewidth=2,
	 color=(hiddenBullCond ? hiddenBullColor : noneColor),
	 display = display.pane,
	 editable = plotHiddenBullRSIInput
	 )

plotshape(
	 hiddenBullCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bullish Label",
	 text=" H Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 editable = plotHiddenBullRSIInput
	 )

plot(
	 phFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bearish",
	 linewidth=2,
	 color=(bearCond ? bearColor : noneColor),
	 display = display.pane,
	 editable = plotBearRSIInput
	 )

plotshape(
	 bearCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Regular Bearish Label",
	 text=" Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 editable = plotBearRSIInput
	 )

plot(
	 phFound and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bearish",
	 linewidth=2,
	 color=(hiddenBearCond ? hiddenBearColor : noneColor),
	 display = display.pane,
	 editable = plotHiddenBearRSIInput
	 )

plotshape(
	 hiddenBearCond and plotRsiInput ? osc[lbRRSIInput] : na,
	 offset=-lbRRSIInput,
	 title="Hidden Bearish Label",
	 text=" H Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 editable = plotHiddenBearRSIInput
	 )
// ====== SMA =========
// ****** Calculs ******
// calcul sma selon choix de la source
sma_var = ta.sma(smaSrcInput, smaLengthInput)
ema_var = ta.ema(smaSrcInput, emaPeriodInput)
sellcondition = ta.crossover(sma_var, ema_var)
buycondition = ta.crossover(ema_var, sma_var)

// ****** Visuels ******
plot(
	plotSmaInput ? sma_var : na, 
	color = color.rgb(20, 62, 96), 
	title = "SMA", 
	offset = smaOffsetInput
)
plot(
	plotSmaInput ? ema_var : na, 
	color = color.red, 
	title = "SMA", 
	offset = smaOffsetInput
)
bgcolor(
	plotSmaInput and sellcondition ? color.orange: na
)
bgcolor(
	plotSmaInput and buycondition ? color.green: na
)
if sellcondition or buycondition
	line.new(
		x1 = bar_index -1,
		y1 = close,
		x2 = bar_index +1,
		y2 = close,
		color = color.black
	)


// ****** Strategies ******

// ****** Alertes ******

alertcondition(
	bullCondAlert, 
	title='Regular Bullish Divergence', 
	message="Found a new Regular Bullish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar")
alertcondition(
	hiddenBullCondAlert, 
	title='Hidden Bullish Divergence', 
	message='Found a new Hidden Bullish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
alertcondition(
	bearCondAlert, 
	title='Regular Bearish Divergence', 
	message='Found a new Regular Bearish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
alertcondition(
	hiddenBearCondAlert, 
	title='Hidden Bearish Divergence', 
	message='Found a new Hidden Bearish Divergence, `Pivot Lookback Right` number of bars to the left of the current bar')
